# Generated by Django 2.0.3 on 2018-03-19 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('spotify_id', models.CharField(max_length=22)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhapsody_web.Artist')),
            ],
        ),
    ]
