# Generated by Django 2.0.3 on 2018-04-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapsody_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song_Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song1_id', models.CharField(max_length=22, null=True)),
                ('song2_id', models.CharField(max_length=22, null=True)),
                ('edge_weight', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='song_graph',
            unique_together={('song1_id', 'song2_id')},
        ),
    ]
