# Generated by Django 2.0.3 on 2018-05-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhapsody_web', '0002_auto_20180430_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
